In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

## these index represents the words in vocab of size 10000
## directly not creating one hot representation instead using indexes

[[9479, 4531, 5840, 1253],
 [9479, 4531, 5840, 5302],
 [9479, 8829, 5840, 6882],
 [1314, 1073, 3142, 4933, 5633],
 [1314, 1073, 3142, 4933, 1109],
 [2605, 9479, 107, 5840, 5471],
 [9371, 9697, 5778, 4933]]

In [9]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [12]:
sent_length=8       #maxlength of sentence (to keep dataset same )
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9479 4531 5840 1253]
 [   0    0    0    0 9479 4531 5840 5302]
 [   0    0    0    0 9479 8829 5840 6882]
 [   0    0    0 1314 1073 3142 4933 5633]
 [   0    0    0 1314 1073 3142 4933 1109]
 [   0    0    0 2605 9479  107 5840 5471]
 [   0    0    0    0 9371 9697 5778 4933]]


In [13]:
## feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/Users/adityakumarsingh/python/venv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step


array([[[ 0.01115944,  0.00142312, -0.03840214,  0.03577589,
          0.0491298 , -0.010794  ,  0.04591933, -0.03709482,
         -0.03004628, -0.00674512],
        [ 0.01115944,  0.00142312, -0.03840214,  0.03577589,
          0.0491298 , -0.010794  ,  0.04591933, -0.03709482,
         -0.03004628, -0.00674512],
        [ 0.01115944,  0.00142312, -0.03840214,  0.03577589,
          0.0491298 , -0.010794  ,  0.04591933, -0.03709482,
         -0.03004628, -0.00674512],
        [ 0.01115944,  0.00142312, -0.03840214,  0.03577589,
          0.0491298 , -0.010794  ,  0.04591933, -0.03709482,
         -0.03004628, -0.00674512],
        [ 0.00306169,  0.02363719,  0.03327053,  0.03341601,
         -0.01877053, -0.02747293, -0.00303843,  0.00589464,
          0.02416563,  0.02986907],
        [ 0.01637689,  0.02093012,  0.03014541,  0.0482075 ,
          0.03560122, -0.02421414, -0.02890247, -0.03645258,
         -0.00439868, -0.01236951],
        [ 0.0008225 ,  0.03099317,  0.04404027, -0.0

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 9479, 4531, 5840, 1253], dtype=int32)

In [25]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[[ 0.01115944,  0.00142312, -0.03840214,  0.03577589,
          0.0491298 , -0.010794  ,  0.04591933, -0.03709482,
         -0.03004628, -0.00674512],
        [ 0.01115944,  0.00142312, -0.03840214,  0.03577589,
          0.0491298 , -0.010794  ,  0.04591933, -0.03709482,
         -0.03004628, -0.00674512],
        [ 0.01115944,  0.00142312, -0.03840214,  0.03577589,
          0.0491298 , -0.010794  ,  0.04591933, -0.03709482,
         -0.03004628, -0.00674512],
        [ 0.01115944,  0.00142312, -0.03840214,  0.03577589,
          0.0491298 , -0.010794  ,  0.04591933, -0.03709482,
         -0.03004628, -0.00674512],
        [ 0.00306169,  0.02363719,  0.03327053,  0.03341601,
         -0.01877053, -0.02747293, -0.00303843,  0.00589464,
          0.02416563,  0.02986907],
        [ 0.01637689,  0.02093012,  0.03014541,  0.0482075 ,
          0.03560122, -0.02421414, -0.02890247, -0.03645258,
         -0.00439868, -0.01236951],
        [ 0.0008225 ,  0.03099317,  0.04404027, -0.0